package com.orderbid.beans;

// Generated Feb 3, 2016 8:51:58 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "PLTORDER")
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String uuid;
	private String additionalFields;
	private Date shipmentDate;
	private Date deliveryDate;
	private Integer destPin;
	private String destAddress;
	private Timestamp lastModifiedDate;
	private Timestamp ordeBidExpiryTime;
	private Timestamp orderDate;
	private String orderNo;
	private String priority;
	private Integer askQuantity;
	private String sourceAddress;
	private String status;
	private Integer sourcePin;
	private Integer updateBy;
	private Integer createBy;
	private Long weight;
	private BigDecimal askRate;
	private String itemSymbol;
	private Integer orderStatus;
	
	
	@Transient
	private Integer rowCount;
	
	public Integer getRowCount() {
		return rowCount;
	}
	public void setRowCount(Integer rowCount) {
		this.rowCount = rowCount;
	}
	private Company company;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID")
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "UUID" )
	public String getUuid() {
		return uuid;
	}
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@Column(name = "ITEM_SYMBOL" )
	public String getItemSymbol() {
		return itemSymbol;
	}
	public void setItemSymbol(String itemSymbol) {
		this.itemSymbol = itemSymbol;
	}
	@Column(name = "ADDITIONAL_FIELDS" )
	public String getAdditionalFields() {
		return additionalFields;
	}
	public void setAdditionalFields(String additionalFields) {
		this.additionalFields = additionalFields;
	}
	@Column(name = "DELIVERY_DATE" )
	public Date getDeliveryDate() {
		return deliveryDate;
	}
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}
	
	@Column(name = "DEST_PIN" )
	public Integer getDestPin() {
		return destPin;
	}
	public void setDestPin(Integer destPin) {
		this.destPin = destPin;
	}
	
	@Column(name = "DEST_ADDRESS" )
	public String getDestAddress() {
		return destAddress;
	}
	public void setDestAddress(String destAddress) {
		this.destAddress = destAddress;
	}
	
	@Column(name = "LAST_MODIFIEDTIME" )
	public Timestamp getLastModifiedDate() {
		return lastModifiedDate;
	}
	public void setLastModifiedDate(Timestamp lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}
	
	@Column(name = "ORDER_BID_EXPIRYTIME" )
	public Timestamp getOrdeBidExpiryTime() {
		return ordeBidExpiryTime;
	}
	public void setOrdeBidExpiryTime(Timestamp ordeBidExpiryTime) {
		this.ordeBidExpiryTime = ordeBidExpiryTime;
	}
	
	@Column(name = "ORDER_DATE" )
	public Timestamp getOrderDate() {
		return orderDate;
	}
	public void setOrderDate(Timestamp orderDate) {
		this.orderDate = orderDate;
	}
	
	@Column(name = "ORDER_NO" )
	public String getOrderNo() {
		return orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	
	@Column(name = "PRIORITY" )
	public String getPriority() {
		return priority;
	}
	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "SOURCE_ADDRESS" )
	public String getSourceAddress() {
		return sourceAddress;
	}
	public void setSourceAddress(String sourceAddress) {
		this.sourceAddress = sourceAddress;
	}
	
	@Column(name = "STATUS" )
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "SOURCE_PIN" )
	public Integer getSourcePin() {
		return sourcePin;
	}
	public void setSourcePin(Integer sourcePin) {
		this.sourcePin = sourcePin;
	}
	
	@Column(name = "UPDATED_BY" )
	public Integer getUpdateBy() {
		return updateBy;
	}
	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}
	
	@Column(name = "CREATED_BY" )
	public Integer getCreateBy() {
		return createBy;
	}
	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}
	
	@ManyToOne
	@JoinColumn(name = "COMPANY_ID", nullable = false)
	public Company getCompany() {
		return company;
	}
	public void setCompany(Company company) {
		this.company = company;
	}
	
	@Column(name = "WEIGHT" )
	public Long getWeight() {
		return weight;
	}
	public void setWeight(Long weight) {
		this.weight = weight;
	}
	@Column(name = "SHIPMENT_DATE" )
	public Date getShipmentDate() {
		return shipmentDate;
	}
	public void setShipmentDate(Date shipmentDate) {
		this.shipmentDate = shipmentDate;
	}
	
	@Column(name = "ASK_QUANTITY" )
	public Integer getAskQuantity() {
		return askQuantity;
	}
	public void setAskQuantity(Integer askQuantity) {
		this.askQuantity = askQuantity;
	}
	
	@Column(name = "ASK_RATE" )
	public BigDecimal getAskRate() {
		return askRate;
	}
	public void setAskRate(BigDecimal askRate) {
		this.askRate = askRate;
	}
	
	@Column(name = "ORDER_STATUS" )
	public Integer getOrderStatus() {
		return orderStatus;
	}
	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}
}
